services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - stack.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
