services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.dev
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
